name: meal_logging
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc:
  
  # Dependency Injection
  get_it:

  # Networking
  dio:

  # Navigation
  go_router:

  # Utilities
  equatable:
  dartz:
  intl:

  google_fonts: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
